---
openapi: 3.0.0
info:
  title: Dibujillo
  description: Especificación de API para pryecto de clase.
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/cristinamaceiras/Dibujillo/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: users
  description: Peticiones para los usuarios (registrados o invitados).
- name: games
  description: Peticiones sobre el juego/partida.
- name: drawings
  description: Peticiones sobre los dibujos
paths:
  /guest:
    post:
      tags:
      - users
      summary: sesión del invitado
      description: obtener la sesión del invitado
      requestBody:
        description: nombre del invitado
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/name'
      responses:
        "201":
          description: invitado creado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sessionToken'
        "400":
          description: faltan parámetros o incorrectos
        "401":
          description: contraseña incorrecta
  /game/{cod}/history:
    get:
      tags:
      - games
      summary: información de la ronda
      description: recuperar información de la ronda actual
      parameters:
      - name: cod
        in: path
        description: codigo de la sala
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: XJW
      - name: sessionToken
        in: header
        description: token del usuario
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: ghnuiredg7983
      responses:
        "200":
          description: funcionamiento correcto
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/historia'
        "401":
          description: token de usuario invalido
        "404":
          description: codigo no existe
  /game/{cod}/player/{name}/drawing/rating:
    put:
      tags:
      - games
      summary: votacion de los dibujos
      description: votar cada dibujo
      parameters:
      - name: cod
        in: path
        description: codigo de la sala
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: XJW
      - name: name
        in: path
        description: nombre del usuario
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: Paco
      - name: sessionToken
        in: header
        description: token del usuario
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: ghnuiredg7983
      requestBody:
        description: puntuación del dibujo
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/rating'
      responses:
        "200":
          description: funcionamiento correcto
        "400":
          description: parámetro mal formado
        "401":
          description: token de usuario invalido
        "404":
          description: codigo o nombre no existen
  /drawings:
    get:
      tags:
      - drawings
      summary: recuperar fotos en el feed de la red social
      description: recuperar los ultimos 20 dibujos compartidos públicamente, de más reciente a más antiguo
      parameters:
      - name: sessionToken
        in: header
        description: token del usuario
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: ghnuiredg7983
      responses:
        "200":
          description: funcionamiento correcto
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/publicacion'
        "401":
          description: token de usuario invalido
components:
  schemas:
    sessionToken:
      required:
      - sessionToken
      type: object
      properties:
        sessionToken:
          type: string
          example: ghnuiredg7983
    name:
      required:
      - name
      type: object
      properties:
        name:
          type: string
          example: Paco
    historia:
      required:
      - history
      - startTime
      type: object
      properties:
        history:
          type: string
          example: Perro sobre un caballo
        startTime:
          type: string
          example: 2022-12-12T04:30:23
    rating:
      required:
      - rating
      type: object
      properties:
        rating:
          type: integer
          example: 3
    publicacion:
      type: array
      items:
        oneOf:
        - type: object
          properties:
            path:
              type: string
              example: /drawings/pepe000002.png
        - type: object
          properties:
            uploadAt:
              type: string
              example: 2022-12-12T04:30:23
        - type: array
          items:
            type: object
            properties:
              user:
                type: string
                example: Cristina
              comment:
                type: string
                example: que bonito
  parameters:
    codigo:
      name: cod
      in: path
      description: codigo de la sala
      required: true
      style: simple
      explode: false
      schema:
        type: string
      example: XJW
    sessionToken:
      name: sessionToken
      in: header
      description: token del usuario
      required: false
      style: simple
      explode: false
      schema:
        type: string
      example: ghnuiredg7983
    nombre:
      name: name
      in: path
      description: nombre del usuario
      required: true
      style: simple
      explode: false
      schema:
        type: string
      example: Paco
